exoticDesign/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('django.contrib.auth.urls')),
    path('users/',include('users.urls')),
    path('services/',include('services.urls')),
    path('',TemplateView.as_view(template_name='home.html'),name='home')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import include,path
from .views import Addimage,RaiseRequest,RaiseRequestDetail,Approve,ApproveDetail,CustomerDataList,GalleryList,AdminApprovedList
urlpatterns =[
   path('image/',Addimage.as_view(),name='addimage'),
   path('request/',RaiseRequest.as_view(),name='raiserequest'),
   path('request_detail/<int:pk>',RaiseRequestDetail.as_view(),name='request_detail'),
    path('approve/',Approve.as_view(),name='approve'),
   path('approve_detail/<int:pk>',ApproveDetail.as_view(),name='approve_detail'),
   path('dashboard/',CustomerDataList.as_view(),name='dashboard'),
   path('listapproved/',AdminApprovedList.as_view(),name='adashboard'),
   path('gallery/',GalleryList.as_view(),name='gallery')
] 

users/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import Signup,ProfileView
urlpatterns=[
    path('signup/',Signup.as_view(),name='signup')      
,path('profile/<int:pk>/',ProfileView.as_view(),name='profile')
]

services/models.py
from django.conf import settings
from django.shortcuts import reverse
from django.db import models
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.core.exceptions import PermissionDenied
from django.utils.translation import ugettext_lazy as _
# Create your models here.
class Category(models.Model):
    title=models.CharField(max_length=300)
    def __str__(self):
        return self.title
class Imagesection(models.Model):
    title=models.CharField(_('Title'),max_length=300)
    image=models.ImageField(upload_to='site_images/',max_length=1000)
    date_added=models.DateField(_('Date Added'),auto_now_add=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    owner=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural=_('Image Section')
    def __str__(self):
        return '{} was added on {}'.format(self.title,self.date_added)
    # def get_absolute_url(self):
    #     return reverse('images-section-detail',kwargs={'pk':self.pk})
    def save(self,*args,**kwargs):
        if(self.owner.is_admin):
            super(Imagesection,self).save()
        else:
            return PermissionDenied
status=((0,'pending'),(1,'approved'),(2,'rejected'))
class Raiserequest(models.Model):
    title=models.CharField(_('Title'),unique=True,max_length=200)
    short_description=models.CharField(_('Short Description'),max_length=400)
    description=models.TextField(_('Detail'))
    related_docs=models.ImageField(upload_to='request/',blank=True,verbose_name=_('Similar Image'))
    status=models.CharField(choices=status,blank=True,max_length=1,default=status[0][0])
    raised_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,verbose_name=_('Raised By'))
    date_updated=models.DateField(_('Last Updated'),auto_now=True)
    date_added=models.DateField(_('Date Added'),auto_now_add=True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('request_detail',args=[str(self.id)])
    @property
    def get_status(self):
        if self.status:
            return status[int(self.status)][1]
    class Meta:
        verbose_name_plural=_('Raise Request')

class Approverequest(models.Model):
    issue=models.OneToOneField(Raiserequest,on_delete=models.CASCADE,verbose_name=_('Request'))
    comment=models.CharField(_('Comment'),unique=True,max_length=500)
    document=models.FileField(upload_to='document/',blank=True)
    date_updated=models.DateField(_('Last Updated'),auto_now=True)
    date_added=models.DateField(_('Date Added'),auto_now_add=True)
    def __str__(self):
        return self.comment
    def get_absolute_url(self):
        return reverse('approve_detail',args=[str(self.id)])
    def save(self,*args,**kwargs):
        self.issue.status=1
        self.issue.save()
        super(Approverequest,self).save(*args,**kwargs)
    class Meta:
        verbose_name_plural=_('Approve Request')

services/forms.py
from django import forms
from .models import Approverequest,Raiserequest
from django.db.models import Q
class ApprovalForm(forms.ModelForm):
    class Meta:
        fields='__all__'
        model=Approverequest
    def __init__(self,*args,**kwargs):
        super(ApprovalForm,self).__init__(*args,**kwargs)
        self.fields['issue'].queryset=Raiserequest.objects.filter(Q(approverequest__isnull=True)|Q(approverequest=self.instance))

services/views.py
from django.shortcuts import reverse
from django.http import HttpResponse
from django.shortcuts import render
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Imagesection,Category,Raiserequest,Approverequest
from django.views.generic import CreateView,DetailView,ListView
from .forms import ApprovalForm


class Addimage(LoginRequiredMixin,CreateView):
    template_name='services/Addimage.html'
    success_url=reverse_lazy('home')
    model=Imagesection
    login_url='login'
    fields=['title','image','category']
    def form_valid(self, form): # new
            form.instance.owner = self.request.user
            return super().form_valid(form)
    def dispatch(self,request,*args,**kwargs):
        if self.request.user.is_admin:
            return super().dispatch(request,*args,**kwargs)
        else:
            raise PermissionDenied
class RaiseRequest(LoginRequiredMixin,CreateView):
    template_name='services/request.html'
    # success_url=reverse_lazy('home')
    model=Raiserequest
    login_url='login'
    fields=['title','short_description','description','related_docs']
    def form_valid(self, form): 
            form.instance.raised_by = self.request.user
            return super().form_valid(form)
    def dispatch(self,request,*args,**kwargs):
        if self.request.user.is_admin:
            raise PermissionDenied
        else:
            return super().dispatch(request,*args,**kwargs)
        
class RaiseRequestDetail(LoginRequiredMixin, DetailView): # new
    model = Raiserequest
    template_name = 'services/request_detail.html'
    login_url = 'login'
    def dispatch(self,request,*args,**kwargs):
        if self.request.user.is_admin:
            raise PermissionDenied
        else:
            return super().dispatch(request,*args,**kwargs)
class Approve(LoginRequiredMixin,CreateView):
    template_name='services/Approve.html'
    form_class=ApprovalForm
    login_url='login'
    def dispatch(self,request,*args,**kwargs):
        if self.request.user.is_admin:
            return super().dispatch(request,*args,**kwargs)
        else:
            raise PermissionDenied

class ApproveDetail(LoginRequiredMixin, DetailView): 
    model=Approverequest
    template_name = 'services/Approve_detail.html'
    login_url = 'login'
    def dispatch(self,request,*args,**kwargs):
        if self.request.user.is_admin:
            return super().dispatch(request,*args,**kwargs)
        else:
            raise PermissionDenied

class CustomerDataList(LoginRequiredMixin,ListView):
    model=Raiserequest
    login_url='login'
    template_name='services/CustomerList.htm'
    def get_queryset(self,*args,**kwargs):
        qs=super().get_queryset(*args,**kwargs) 
        return qs.filter(raised_by=self.request.user).order_by('status')
        # return qs
class AdminApprovedList(LoginRequiredMixin,ListView):
    model=Raiserequest
    login_url='login'
    template_name='services/CustomerList.htm'
    def get_queryset(self,*args,**kwargs):
        qs=super().get_queryset(*args,**kwargs) 
        return qs.filter().order_by('status')
class GalleryList(ListView):
    model=Imagesection
    login_url='login'
    template_name='services/Gallery.html'

templates/services/Addimage.html
{% extends 'base.html' %}
{% block content %}
<style>
.input,.select {
  width:80%;
}
</style>
<div class='columns is-desktop is-mobile'>
<div class="column">
<h1 style="color:white;font-size:40px;text-align:center;font-family:'Lobster', cursive;">Add Image</h1>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="field">
        <label class="label" style="color: white;font-size: 20px;">Title</label>
        <div class="control">
          <input class="input" type="text" name="title" id='id_title'>
        </div>
</div>

<div class="field">
        <label class="label " style="color: white;font-size: 20px;">Category</label>
        <div class="control">
          <div class="select" style="width: 100%;">
                {{form.category}}
              </div>
        </div>
</div>
<div class="field">
  <div id="file-js-example" class="file has-name is-primary ">
    <label class="file-label" style="width: 80%;">
      <input class="file-input photo" type="file"  id='id_image' name="image" accept="image/*">
      <span class="file-cta" >
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label" >
          Add Image
        </span>
      </span>
      <span class="file-name" style="width: 40%;">
        No file uploaded
      </span>
    </label>
  </div>
</div>
  
<input type="submit" class='button is-success' value="submit Now" />
</form>
</div>
<div class="column"></div>
</div>
<script>

        const fileInput = document.querySelector('#file-js-example input[type=file]');
        fileInput.onchange = () => {
          if (fileInput.files.length > 0) {
            const fileName = document.querySelector('#file-js-example .file-name');
            fileName.textContent = fileInput.files[0].name;
          }
        }
        $(document).ready(function(){
            $('#id_category').addClass('select')
        })
 </script>
{% endblock content%}

templates/services/Approve.html
{% extends 'base.html' %}
{% block content %}
  <style>
    .input,.select{
      width: 80%;
    }
  @media only screen and (max-width: 375px) {
  .columns{
    display: flex;
    align-content: center;
    justify-content: center;
  }
  .column{
    /* background: red; */
   width:7px;
  }
  
    
  }

 
  </style>
<div class='columns is-desktop is-mobile'>
<!-- <div class='column'></div> -->
<div class="column hide">
<h1 style='font-size:30px;color: white; font-family: Lobster';>Approve Request</h1>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="field">
        <label class="label" style="color: white;">Comment</label>
        <div class="control">
          <input class="input" type="text" name="comment" id='id_comment'>
        </div>
</div>

<div class="field">
  <div id="file-js-example" class="file has-name is-primary is-centered" style="width: 80%;">
    <label class="file-label">
      <input class="file-input photo" type="file"  id='id_document' name="document" >
      <span class="file-cta" style="width: 50%;">
        <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              Upload Document
            </span>
          </span>
          <span class="file-name" style="color: white;">
            No file uploaded
          </span>
        </label>
      </div>
    </div>
      
<div class="field" >
        <label class="label has-text-primary">Requested By</label>
        <div class="control">
          <div class="select" style="width: 80%;">
                {{form.issue}}
              </div>
        </div>
</div>
<input type="submit" class='button is-danger' value="submit Now" />
</form>
</div>
<!-- <div class="column"></div> -->
</div>
<script>
        const fileInput = document.querySelector('#file-js-example input[type=file]');
        fileInput.onchange = () => {
          if (fileInput.files.length > 0) {
            const fileName = document.querySelector('#file-js-example .file-name');
            fileName.textContent = fileInput.files[0].name;
          }
        }
        $(document).ready(function(){
            $('#id_issue').addClass('select').addClass('is_large')
        })
        </script>
{% endblock content%}

templates/services/Approve_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
.img{
 height: 100px;
 width: 100px;
 border-radius: 360px;
 border:2px solid black;
 filter:brightness(140%);
}
.div{
    padding: 10px;
    background:linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.8));
}
.img:hover{
  transform: scale(1.1);
}
.img ~ a{
    color: green;
    font-size: 30px;
    position: relative;
    top:-50px;
}
h1{
    color:white;
    font-size: 40px;
}
</style>
<div class='columns is-desktop'>
<div class="column"></div>
<div class="column">
<div class="div has-text-centered" >
<h1>Approval Details</h1>
<img class='img'  src="{{object.issue.raised_by.profile.pic.url}}" >
<a href='{% url 'profile' pk=object.issue.raised_by.profile.pk %}' class='has-text-primary' >{{object.issue.raised_by.name}}</a>
<p>Short Description : {{object.issue.short_description}}</p>
<p>{{object.comment}}</p>
<p>Date : {{object.date_added}}</p>
<p>File generated on :{{object.date_updated}} <a href='{{object.document.url}}' class='has-text-danger' target="_blank">Download File</a> </p>
</div>
</div>
</div>
{% endblock content%}

templates/services/CustomerList.htm
{% extends "base.html" %}
{% block content %}
<style>

table { 
  width: 100%; 
  border-collapse: collapse; 
  color:rgb(75, 0, 110);
  border:3px solid rgb(255, 244, 90);
}
tr:nth-of-type(odd) { 
  background: #eee; 
}
tr:nth-of-type(even) { 
  background: #eee; 
}
th { 
 color:#ccc;
  background:rgb(66, 186, 241); 
}
td, th { 
  text-align: center;
  padding: 6px; 
  /* border: 1px solid #ccc;  */
  text-align: left; 
}

h1{
  color:white;
}
@media only screen and (max-width: 375px){
  table, thead, tbody, th, td, tr { 
		display: block;

	}
   table{
    border:3px dotted #ff2922;
   }
	thead tr { 
		position: absolute;
		top: -9999px;
		left: -9999px;
	}
	
	tr { border: 1px solid #ccc; }
	
	td { 
		border: none;
		border-bottom: 1px solid #eee; 
		position: relative;
		padding-left: 50%; 
	}

  td:before { 
		position: absolute;
		top: 6px;
		left: 6px;
		width: 45%; 
		padding-right: 10px; 
		white-space: nowrap;
	}
	td:nth-of-type(1):before { content: "ID"; }
	td:nth-of-type(2):before { content: "Date Creted"; }
	td:nth-of-type(3):before { content: "Title"; }
	td:nth-of-type(4):before { content: "Summary "; }
	td:nth-of-type(5):before { content: "Related File link"; }
	td:nth-of-type(6):before { content: "Status"; }
	td:nth-of-type(7):before { content: "Download Link"; }
	td:nth-of-type(8):before { content: "Generated On"; }
	td:nth-of-type(9):before { content: "Requested By"; }
}


/* This type of table styling is taken from url https://css-tricks.com/responsive-data-tables */

</style>
<div class="columns is-desktop is-mobile">
  <div class='column' style="overflow-x:auto;">
    {% if user.is_admin %}
    <h1 style='font-size:30px' class="has-text-centered">Approved By Me</h1>
    {% else %}
    <h1 style='font-size:30px' class="has-text-centered">My Orders</h1>
    {% endif %}
    <table>
      <thead>
        <tr><th style="color:white;">ID</th><th style="color:white;">Date Requested</th><th style="color:white;">Title</th><th style="color:white;">Short Description</th><th style="color:white;">Related File</th><th style="color:white;">Status</th><th style="color:white;">Download Link</th><th style="color:white;">Generated on</th>{% if request.user.is_superuser %}<th style="color:white;">Requested By</th> {% else %} {% endif %}</tr>
      </thead>
      <tbody>
        {% for obj in object_list %}
        <tr>
          <td>{{obj.id}}</td>
          <td>{{obj.date_added}}</td>
          <td>{{obj.title}}</td>
          <td>{{obj.short_description}}</td>
          <td><a href="{{obj.related_docs.url}}" class='has-text-primary' target="_blank" >View file</a></td>
          <td>{{obj.get_status}}</td>
          {% if obj.status == '1' %}
          <td><a href="{{obj.approverequest.document.url}}" class='has-text-primary' target="_blank" >Download file</a></td>
          <td>{{obj.approverequest.date_added}}</td>
          {% else %}
          <td>---</td>
          <td>---</td>
          {% endif %}
          {% if request.user.is_superuser %}
           <td>{{obj.raised_by.name}}</td>
          {% else %}
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

templates/services/Gallery.html
{% extends "base.html" %}
{% load static %}
{% block content%}
<style>
.gallery{
    display:flex;
    flex:1 1 auto;
    align-content: space-around;
    justify-content: space-evenly;
    flex-wrap: wrap;
    text-align: center;
    flex-shrink: initial;
  flex-direction:row-reverse;
}
.div{
  margin:5px;
  padding:5px;
}
.image{
    filter: brightness(10%) contrast(100%) blur(-100px) ;
    height: 300px;
    width:auto;
    border-radius: 10px ;
    border:2px solid white;
    
}
.image:hover{
    animation: justflip;
    background: transparent;
    animation-direction: alternate-reverse;
    animation-duration: 500ms;
    animation-iteration-count: inherit;
    animation-timing-function: ease-in;
}
.image:hover div{
    background: transparent;
}

.hero-body{
  
  background: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),url('{% static "img/background.jpg" %}');
        background-size: auto;
    } 

@keyframes justflip{
  100%{
    transform: scale(1.01);
  }
  75%{
    transform: scale(1.1);
  }
  50%{
    transform: scale(1.2);
  }
  50%{
    transform: scale(1.25);
  }
  0%{
    transform: scale(1.3);
  }
}
</style>
<div class="gallery">
{% for obj in object_list %}
<div class='div' style="margin: 5px;">
<img class='image' src='{{obj.image.url}}' >
<p style="color: thistle;">@{{obj.owner.name}}</p>
<p style="color: thistle;">#{{obj.category.title}} - {{obj.date_added}}</p>
</div>

{% endfor %}
</div>
{% endblock content%}

templates/services/Resume.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
</head>
<body>
</body>
</html>

templates/services/request.html
{% extends 'base.html' %}
{% block content %}
<style>
  @media only screen and (max-width:375px) {

  }

</style>


<div class='columns is-desktop is-mobile'>
<!-- <div class='column'></div>  -->
<div class="column second is-two-thirds">
<h1 style="color: white;font-size: 35px;text-align: center;">Request</h1>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="field">
        <label class="label has-text-primary">Title</label>
        <div class="control">
          <input class="input" type="text" name="title" id='id_title'>
        </div>
</div>

<div class="field">
        <label class="label has-text-primary">Short Description</label>
        <div class="control">
          <input class="input" type="text" name="short_description" id='id_short_description' >
        </div>
</div>


<div class="field">
        <label class="label has-text-primary">Description</label>
        <div class="control">
          <textarea class="input textarea" name="description" id='id_description'></textarea>
</div>
</div>
<div class="field">

  <div id="file-js-example" class="file has-name is-primary is-centered">
    <label class="file-label">
      <input class="file-input photo" type="file"  id='id_related_docs' name="related_docs" accept="image/*">
      <span class="file-cta" style="width: 50%;" >
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          Upload Related Image
        </span>
      </span>
      <span class="file-name">
        No file uploaded
      </span>
    </label>
  </div>
</div>
  <p></p>
  <input type="submit" class='button is-info' value="submit Now" />
</form>
</div>
<div class="column"></div>
</div>
<script>
        const fileInput = document.querySelector('#file-js-example input[type=file]');
        fileInput.onchange = () => {
          if (fileInput.files.length > 0) {
            const fileName = document.querySelector('#file-js-example .file-name');
            fileName.textContent = fileInput.files[0].name;
          }
        }
        
        </script>
{% endblock content%}

templates/services/request_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
.detail{
    color:white;
    /* text-align: center; */
    font-size: 18px;
}
.columns{
    display: flex;
    justify-content: center;
    align-items: center;
}
img{
    border:2px solid white;
}

</style>
<div class="columns is-mobile is-desktop">
  <div class="column detail">
      <h1 style="font:500;font-size: 30px;" >Detail Of Request</h1>
      <p>Title --<span style="color:yellow"> {{object.title}}</span></p>
      <p>Short Description --<span style="color:yellow"> {{object.short_description}}</span></p>
      <p>Description --<span style="color:yellow"> {{object.description}}</span></p>
      <p>Date Requested --<span style="color:yellow">{{object.date_added}}</span></p>
      <p>Date Updated --<span style="color:yellow">{{object.date_updated}}</span></p>
      <img src="{{object.related_docs.url}}" height="300" width="400">
    </div>
</div>
    {% endblock content%}